package com.miaoshaproject.dao;

import com.miaoshaproject.dataObject.itemDO;

public interface itemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int insert(itemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int insertSelective(itemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    itemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int updateByPrimaryKeySelective(itemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int updateByPrimaryKey(itemDO record);
}