package com.miaoshaproject.dao;

import com.miaoshaproject.dataObject.itemStockDO;

public interface itemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int insert(itemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int insertSelective(itemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    itemStockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int updateByPrimaryKeySelective(itemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jan 03 21:13:30 CST 2019
     */
    int updateByPrimaryKey(itemStockDO record);
}